server:
  port: 8085
#  servlet:
#    context-path: /test06

spring:
  profiles:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    hidden-method:
      filter:
        enabled: true
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tsherpa
    username: root
    password: 1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.chunjae.test06.entity
  mapper-locations: mappers/**/*.xml

logging:
  config: classpath:logback.xml